Slurm
Tole-k/SageML pull request #72
Opened 2024-12-21 20:00 UTC by Dawid64

2024-12-24 12:47 UTC, Tole-k commented
important note, OneHotEncoder does nothing to target feature at the moment, it just returns it unchanged because it doesn't really make sense to transform it this way, moreover it would convert target from 1D pd.Series into 2D pd.Dataframe. To process target feature we have LabelEncoder which mitigates this problem while still encoding strings into numeric values

2024-12-24 12:56 UTC, Tole-k commented
I believe we wanted to remove CatBoost from our project over ties with Russia, I actually have already done it but on the "algorithms" branch which never got merged

2024-12-24 13:03 UTC, Tole-k commented
It would be nice to have an option to extract both Statistical and Topological features but get_sota_meta_features returns one or the other

2024-12-24 13:54 UTC, Tole-k requested changes

2024-12-24 13:54 UTC, Tole-k commented on turbo_ml/meta_learning/dataset_parameters/sota.py
It would be nice to have an option to extract both Statistical and Topological features but get_sota_meta_features returns one or the other

2024-12-24 13:54 UTC, Tole-k commented on turbo_ml/workflow/extract_parameters.py
important note, OneHotEncoder does nothing to target feature at the moment, it just returns it unchanged because it doesn't really make sense to transform it this way, moreover it would convert target from 1D pd.Series into 2D pd.Dataframe. To process target feature we have LabelEncoder which mitigates this problem while still encoding strings into numeric values

2024-12-24 13:54 UTC, Tole-k commented on turbo_ml/algorithms/cat_boost.py
I believe we wanted to remove CatBoost from our project over ties with Russia, I actually have already done it but on the "algorithms" branch which never got merged

2024-12-24 13:54 UTC, Tole-k commented on turbo_ml/workflow/algorithms_evaluations.py
Why is slice index being mutliplied by 10 here?

2024-12-30 15:13 UTC, Dawid64 commented on turbo_ml/workflow/extract_parameters.py
Can you combine OHE and label encoder into one? such that we can pass encoders as one list for both data and target, we can alternately make an argument for OHE / Label if should it change target or data, unless you have some other propositions

2025-01-02 12:18 UTC, Tole-k commented on turbo_ml/workflow/extract_parameters.py
Yes, i have added label_encoder functionality to one_how_encoder, and renamed it to just 'encoder' not to mislead

2025-01-11 15:32 UTC, adamtms commented on requirements.txt
> +scikit-learn
During prediction we have static amount of scikit-learn models defined in the file but during training it is chosen automatically. Maybe we should choose specific scikit-learn version so the number of models would not change or have the available models available for predicition also chosen dynamically not hard-coded.

2025-01-14 08:08 UTC, Dawid64 commented on requirements.txt
> +scikit-learn
Good idea the best idea is probably saving models into pickle together with preprocessing and config

2025-01-18 22:23 UTC, Tole-k commented on turbo_ml/meta_learning/meta_model_search.py
I am wondering shouldn't the order of __MODELS_NAMES__ match the order of columns in algorithm_results.csv ?, because i don't think it does

2025-01-19 17:34 UTC, Tole-k commented on turbo_ml/meta_learning/meta_model_search.py
> +__MODELS_NAMES__ = ["NeuralNetworkModel", "XGBoostClassifier", "AdaBoostClassifier", "BaggingClassifier", "BernoulliNB", "CalibratedClassifierCV", "CategoricalNB", "ComplementNB", "DecisionTreeClassi
I am wondering shouldn't the order of MODELS_NAMES match the order of columns in algorithm_results.csv ?, because i don't think it does

What's worse is that i believe it uses this __MODELS_NAMES__ while predicting even when the model was trained on algorithm_families and not our sklearn algorithms, so it takes an index of best performing families and returns __MODEL_NAME__ associated with it which results i total gibberish being returned

ehh, i think we need to deliniate stronger between our system behavoiur when working with family scores and algorithm scores

2025-05-03 11:28 UTC, merged